services:

  product-catalog:
    build:
      context: ./product_catalog
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./product_catalog:/code
    ports:
      - "8090:8090"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=zaeem
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=product_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  postgres_db:
   driver: local
