FROM python:3.12

WORKDIR /code

COPY . /code

RUN pip install poetry

RUN poetry config virtualenvs.create false

RUN poetry install

EXPOSE 8090

CMD ["poetry", "run", "uvicorn", "product_catalog.main:app", "--host", "0.0.0.0", "--port", "8090"]